version: '3.8'

services:
  mysql_container:
    container_name: allwell_db
    hostname: allwell
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"
